/**
 * Project Documenter - Generates PROJECT_LOG.md after project completion
 * 
 * Creates a detailed markdown document of what was built, including:
 * - Project overview
 * - Files created/modified
 * - Technologies used
 * - Build history
 * - How to run
 * - Future improvements
 */

import * as fs from 'fs';
import * as path from 'path';
import { ProjectEntry, BuildEntry } from './project-registry';

export interface DocumentOptions {
  projectPath: string;
  projectName: string;
  description: string;
  files: string[];
  technologies: string[];
  buildHistory: BuildEntry[];
  originalPrompt: string;
  isUpdate: boolean;
}

export class ProjectDocumenter {
  /**
   * Generate PROJECT_LOG.md for a completed project
   */
  static generateProjectLog(options: DocumentOptions): string {
    const now = new Date();
    const timestamp = now.toISOString().split('T')[0];
    const time = now.toTimeString().split(' ')[0];

    let doc = `# ${options.projectName}\n\n`;
    doc += `> Generated by AgentPrime on ${timestamp} at ${time}\n\n`;
    
    // Description
    doc += `## 📋 Overview\n\n`;
    doc += `${options.description}\n\n`;
    
    // Original Request
    doc += `## 💬 Original Request\n\n`;
    doc += `> ${options.originalPrompt.replace(/\n/g, '\n> ')}\n\n`;
    
    // Technologies
    if (options.technologies.length > 0) {
      doc += `## 🛠️ Technologies Used\n\n`;
      options.technologies.forEach(tech => {
        doc += `- ${tech}\n`;
      });
      doc += `\n`;
    }
    
    // Files
    doc += `## 📁 Project Structure\n\n`;
    doc += `\`\`\`\n`;
    doc += this.generateFileTree(options.files);
    doc += `\`\`\`\n\n`;
    
    // File descriptions
    doc += `### File Descriptions\n\n`;
    for (const file of options.files) {
      const ext = path.extname(file);
      const icon = this.getFileIcon(ext);
      doc += `- ${icon} **\`${file}\`** - ${this.describeFile(file)}\n`;
    }
    doc += `\n`;
    
    // Build History
    if (options.buildHistory.length > 0) {
      doc += `## 📜 Build History\n\n`;
      for (const entry of options.buildHistory) {
        const date = new Date(entry.timestamp).toLocaleString();
        const actionEmoji = this.getActionEmoji(entry.action);
        doc += `### ${actionEmoji} ${this.capitalize(entry.action)} - ${date}\n\n`;
        doc += `**Description:** ${entry.description}\n\n`;
        if (entry.filesChanged.length > 0) {
          doc += `**Files Changed:**\n`;
          entry.filesChanged.forEach(f => {
            doc += `- \`${f}\`\n`;
          });
          doc += `\n`;
        }
      }
    }
    
    // How to Run
    doc += `## 🚀 How to Run\n\n`;
    doc += this.generateRunInstructions(options);
    
    // Future Improvements
    doc += `## 💡 Potential Improvements\n\n`;
    doc += this.suggestImprovements(options);
    
    // Footer
    doc += `---\n\n`;
    doc += `*This document was automatically generated by AgentPrime's Mirror Intelligence System.*\n`;
    doc += `*Last updated: ${now.toISOString()}*\n`;
    
    return doc;
  }

  /**
   * Write PROJECT_LOG.md to the project directory
   */
  static writeProjectLog(projectPath: string, options: DocumentOptions): string {
    const content = this.generateProjectLog(options);
    const logPath = path.join(projectPath, 'PROJECT_LOG.md');
    
    // If file exists, append to build history section
    if (fs.existsSync(logPath) && options.isUpdate) {
      // For updates, regenerate the whole file with updated history
      fs.writeFileSync(logPath, content, 'utf-8');
    } else {
      fs.writeFileSync(logPath, content, 'utf-8');
    }
    
    return logPath;
  }

  /**
   * Generate a simple file tree
   */
  private static generateFileTree(files: string[]): string {
    // Sort files by path
    const sorted = [...files].sort();
    let tree = '';
    
    for (const file of sorted) {
      const depth = file.split('/').length - 1;
      const indent = '  '.repeat(depth);
      const name = path.basename(file);
      tree += `${indent}${name}\n`;
    }
    
    return tree || 'No files created\n';
  }

  /**
   * Get an emoji icon for file type
   */
  private static getFileIcon(ext: string): string {
    const icons: Record<string, string> = {
      '.html': '🌐',
      '.css': '🎨',
      '.js': '⚡',
      '.ts': '💎',
      '.jsx': '⚛️',
      '.tsx': '⚛️',
      '.json': '📋',
      '.md': '📝',
      '.py': '🐍',
      '.sql': '🗃️',
      '.sh': '🖥️',
      '.yml': '⚙️',
      '.yaml': '⚙️',
      '.env': '🔒',
      '.png': '🖼️',
      '.jpg': '🖼️',
      '.svg': '🎭'
    };
    return icons[ext] || '📄';
  }

  /**
   * Generate a description for a file based on its name
   */
  private static describeFile(file: string): string {
    const name = path.basename(file).toLowerCase();
    const ext = path.extname(file);
    
    // Common file descriptions
    const descriptions: Record<string, string> = {
      'index.html': 'Main HTML entry point',
      'styles.css': 'Primary stylesheet',
      'style.css': 'Primary stylesheet',
      'script.js': 'Main JavaScript logic',
      'app.js': 'Application entry point',
      'main.js': 'Main module',
      'game.js': 'Game logic and mechanics',
      'package.json': 'Node.js project configuration',
      'readme.md': 'Project documentation',
      'project_log.md': 'Build history and documentation',
      '.gitignore': 'Git ignore configuration',
      'tsconfig.json': 'TypeScript configuration',
      'vite.config.js': 'Vite build configuration',
      'requirements.txt': 'Python dependencies',
      'main.py': 'Python main module',
      'app.py': 'Python application entry'
    };
    
    if (descriptions[name]) {
      return descriptions[name];
    }
    
    // Default descriptions by extension
    const extDescriptions: Record<string, string> = {
      '.html': 'HTML page',
      '.css': 'Stylesheet',
      '.js': 'JavaScript module',
      '.ts': 'TypeScript module',
      '.json': 'JSON configuration',
      '.py': 'Python module',
      '.md': 'Markdown documentation'
    };
    
    return extDescriptions[ext] || 'Project file';
  }

  /**
   * Get emoji for build action
   */
  private static getActionEmoji(action: string): string {
    const emojis: Record<string, string> = {
      'create': '🆕',
      'update': '🔄',
      'fix': '🔧',
      'enhance': '✨'
    };
    return emojis[action] || '📝';
  }

  /**
   * Capitalize first letter
   */
  private static capitalize(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  /**
   * Generate run instructions based on project type
   */
  private static generateRunInstructions(options: DocumentOptions): string {
    const hasPackageJson = options.files.includes('package.json');
    const hasIndexHtml = options.files.some(f => f.includes('index.html'));
    const hasPython = options.files.some(f => f.endsWith('.py'));
    const hasRequirements = options.files.includes('requirements.txt');
    
    let instructions = '';
    
    if (hasPackageJson) {
      instructions += `### Node.js Project\n\n`;
      instructions += `1. Install dependencies:\n`;
      instructions += `   \`\`\`bash\n   npm install\n   \`\`\`\n\n`;
      instructions += `2. Start the project:\n`;
      instructions += `   \`\`\`bash\n   npm start\n   \`\`\`\n\n`;
    }
    
    if (hasIndexHtml && !hasPackageJson) {
      instructions += `### Static Website\n\n`;
      instructions += `Open \`index.html\` directly in your browser, or use a local server:\n\n`;
      instructions += `\`\`\`bash\n`;
      instructions += `# Using Python\n`;
      instructions += `python -m http.server 8080\n\n`;
      instructions += `# Using Node.js\n`;
      instructions += `npx serve .\n`;
      instructions += `\`\`\`\n\n`;
    }
    
    if (hasPython) {
      instructions += `### Python Project\n\n`;
      if (hasRequirements) {
        instructions += `1. Create virtual environment:\n`;
        instructions += `   \`\`\`bash\n   python -m venv venv\n   source venv/bin/activate  # or venv\\Scripts\\activate on Windows\n   \`\`\`\n\n`;
        instructions += `2. Install dependencies:\n`;
        instructions += `   \`\`\`bash\n   pip install -r requirements.txt\n   \`\`\`\n\n`;
      }
      const mainFile = options.files.find(f => f.endsWith('.py')) || 'main.py';
      instructions += `3. Run the project:\n`;
      instructions += `   \`\`\`bash\n   python ${mainFile}\n   \`\`\`\n\n`;
    }
    
    if (!instructions) {
      instructions = `Refer to the project files for specific run instructions.\n\n`;
    }
    
    return instructions;
  }

  /**
   * Suggest potential improvements based on project
   */
  private static suggestImprovements(options: DocumentOptions): string {
    const suggestions: string[] = [];
    
    // Check for missing common files
    if (!options.files.includes('README.md') && !options.files.includes('readme.md')) {
      suggestions.push('Add a README.md with project documentation');
    }
    
    if (!options.files.includes('.gitignore')) {
      suggestions.push('Add a .gitignore file for version control');
    }
    
    // Tech-specific suggestions
    if (options.technologies.includes('JavaScript') && !options.technologies.includes('TypeScript')) {
      suggestions.push('Consider migrating to TypeScript for better type safety');
    }
    
    if (options.files.some(f => f.endsWith('.html'))) {
      suggestions.push('Add responsive design for mobile devices');
      suggestions.push('Implement accessibility improvements (ARIA labels, keyboard navigation)');
    }
    
    if (options.technologies.includes('React') || options.technologies.includes('Vue')) {
      suggestions.push('Add unit tests with Jest or Vitest');
      suggestions.push('Implement state management (Redux, Zustand, or Pinia)');
    }
    
    // General suggestions
    suggestions.push('Add error handling and loading states');
    suggestions.push('Implement dark/light theme toggle');
    
    // Format as markdown list
    let md = '';
    suggestions.slice(0, 5).forEach(s => {
      md += `- [ ] ${s}\n`;
    });
    md += `\n`;
    
    return md;
  }
}

