/**
 * Smart Mode Types
 * TypeScript interfaces for the Matrix Smart Mode intelligence system
 */

/**
 * Intelligence levels for the Matrix Agent
 * - basic: Literal execution - does exactly what user says
 * - smart: Intent understanding - understands context, fills gaps
 * - genius: Proactive enhancement - anticipates needs, adds improvements
 */
export type IntelligenceLevel = 'basic' | 'smart' | 'genius';

/**
 * Enhancement types that can be applied to user requests
 */
export type EnhancementType = 
  | 'quality'        // Better patterns, cleaner structure
  | 'error-handling' // Try/catch, validation, fallbacks
  | 'edge-case'      // Null checks, boundary conditions
  | 'security'       // Input sanitization, CSRF, etc.
  | 'testing'        // Suggests or adds test cases
  | 'docs'           // Helpful comments and documentation
  | 'accessibility'  // A11y improvements
  | 'performance'    // Optimization suggestions
  | 'ux';            // User experience improvements

/**
 * Priority levels for enhancements
 */
export type EnhancementPriority = 'high' | 'medium' | 'low';

/**
 * An enhancement suggestion generated by the Enhancement Engine
 */
export interface Enhancement {
  /** Type of enhancement */
  type: EnhancementType;
  /** Human-readable description of what this enhancement does */
  description: string;
  /** Priority level - high priority enhancements are always applied in Smart+ modes */
  priority: EnhancementPriority;
  /** Whether this can be applied automatically without asking user */
  autoApply: boolean;
  /** Optional code snippet or example */
  example?: string;
  /** Category for grouping related enhancements */
  category?: string;
}

/**
 * Context clue extracted from conversation or user patterns
 */
export interface ContextClue {
  /** Type of context (preference, history, project, etc.) */
  type: 'preference' | 'history' | 'project' | 'conversation';
  /** The actual clue/insight */
  content: string;
  /** Confidence score 0-1 */
  confidence: number;
  /** Source of this clue */
  source?: string;
}

/**
 * Result of analyzing user intent
 */
export interface IntentAnalysis {
  /** The original message from the user */
  literalRequest: string;
  /** What the user actually wants to achieve */
  trueIntent: string;
  /** Requirements not explicitly stated but implied */
  implicitRequirements: string[];
  /** Suggested enhancements based on the intent */
  suggestedEnhancements: Enhancement[];
  /** Confidence score for the analysis (0-1) */
  confidenceScore: number;
  /** Context clues used in the analysis */
  contextClues: ContextClue[];
  /** Detected task type */
  taskType?: TaskType;
  /** Keywords extracted from the request */
  keywords: string[];
  /** Whether this is a follow-up to a previous request */
  isFollowUp: boolean;
}

/**
 * Task types that can be detected from user requests
 */
export type TaskType = 
  | 'code-generation'   // Creating new code
  | 'code-modification' // Modifying existing code
  | 'debugging'         // Finding and fixing bugs
  | 'refactoring'       // Improving code structure
  | 'documentation'     // Writing docs/comments
  | 'testing'           // Creating tests
  | 'ui-design'         // UI/UX work
  | 'api-design'        // API/backend work
  | 'system-action'     // System control actions
  | 'web-search'        // Information lookup
  | 'general';          // General chat/questions

/**
 * Conversation context passed to the intent analyzer
 */
export interface ConversationContext {
  /** Previous messages in the conversation */
  history: ConversationMessage[];
  /** Current workspace/project path */
  workspacePath?: string;
  /** Files in the current project */
  projectFiles?: string[];
  /** Active file being edited */
  activeFile?: string;
  /** User preferences from Mirror Memory */
  userPreferences?: UserPreference[];
  /** Recent successful patterns */
  successPatterns?: string[];
  /** Anti-patterns to avoid */
  antiPatterns?: string[];
}

/**
 * A message in the conversation history
 */
export interface ConversationMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
}

/**
 * User preference stored in Mirror Memory
 */
export interface UserPreference {
  /** Category of preference */
  category: 'code-style' | 'framework' | 'naming' | 'structure' | 'tools' | 'general';
  /** The preference key */
  key: string;
  /** The preference value */
  value: string;
  /** Confidence based on how often this preference was observed */
  confidence: number;
  /** Last time this preference was used */
  lastUsed: number;
}

/**
 * Result from the Enhancement Engine
 */
export interface EnhancementResult {
  /** The original request */
  originalRequest: string;
  /** Enhanced prompt to send to the AI */
  enhancedPrompt: string;
  /** List of enhancements that were applied */
  appliedEnhancements: Enhancement[];
  /** List of enhancements suggested but not auto-applied */
  suggestedEnhancements: Enhancement[];
  /** Intelligence level used */
  intelligenceLevel: IntelligenceLevel;
  /** Processing metadata */
  metadata: {
    processingTimeMs: number;
    enhancementsConsidered: number;
    enhancementsApplied: number;
  };
}

/**
 * Configuration for the Smart Mode processor
 */
export interface SmartModeConfig {
  /** Default intelligence level */
  defaultLevel: IntelligenceLevel;
  /** Whether to learn from user feedback */
  learningEnabled: boolean;
  /** Maximum enhancements to apply per request */
  maxEnhancements: number;
  /** Minimum confidence to auto-apply enhancements */
  minAutoApplyConfidence: number;
  /** Whether to show enhancement explanations to user */
  showExplanations: boolean;
}

/**
 * Feedback from user on an enhancement
 */
export interface EnhancementFeedback {
  /** ID of the enhancement */
  enhancementId: string;
  /** Whether user liked the enhancement */
  liked: boolean;
  /** Optional reason */
  reason?: string;
  /** Timestamp */
  timestamp: number;
}

/**
 * Smart Mode processing result
 */
export interface SmartModeResult {
  /** The analysis of user intent */
  intentAnalysis: IntentAnalysis;
  /** Enhancement result with modified prompt */
  enhancementResult: EnhancementResult;
  /** Whether processing was successful */
  success: boolean;
  /** Error message if failed */
  error?: string;
}
